name: Check-Build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['7.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
          
      - name: Add MSYS64 bin to PATH
        run: echo "C:\msys64\usr\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.1

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: latest

      - name: Restore NuGet packages
        run: nuget restore Amethyst.NET.sln

      - name: Build (publish) K2CrashHandler
        run: msbuild K2CrashHandler /restore /p:Platform=x64 /p:PlatformTarget=x64 /p:Configuration=Release /p:RuntimeIdentifier=win10-x64 /t:Publish /p:PublishProfile=K2CrashHandler\Properties\PublishProfiles\FolderProfile.pubxml
        
      - name: Build (publish) Amethyst.NET
        run: msbuild Amethyst /restore /p:Platform=x64 /p:PlatformTarget=x64 /p:Configuration=Release /p:RuntimeIdentifier=win10-x64 /t:Publish /p:PublishProfile=Amethyst\Properties\PublishProfiles\FolderProfile.pubxml
        
      - name: Create a shared output
        run: |
          Copy-Item -Path Amethyst\bin\Release\net7.0\win10-x64\publish -Destination Pack\Output -Recurse
          Copy-Item -Path K2CrashHandler\bin\Release\net7.0\win10-x64\publish -Destination Pack\Output\K2CrashHandler -Recurse

      - name: Download Kinect V1 plugin
        uses: robinraju/release-downloader@v1.6
        with: 
          repository: "KinectToVR/plugin_KinectV1"
          latest: true
          fileName: "plugin_KinectV1.zip"
          out-file-path: "Pack/Zip/"
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Download Kinect V2 plugin
        uses: robinraju/release-downloader@v1.6
        with: 
          repository: "KinectToVR/plugin_KinectV2"
          latest: true
          fileName: "plugin_KinectV2.zip"
          out-file-path: "Pack/Zip/"
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Download PSMoveService plugin
        uses: robinraju/release-downloader@v1.6
        with: 
          repository: "KinectToVR/plugin_PSMoveService"
          latest: true
          fileName: "plugin_PSMoveService.zip"
          out-file-path: "Pack/Zip/"
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Download owoTrackVR plugin
        uses: robinraju/release-downloader@v1.6
        with: 
          repository: "KinectToVR/plugin_owoTrackVR"
          latest: true
          fileName: "plugin_owoTrackVR.zip"
          out-file-path: "Pack/Zip/"
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Download OpenVR plugin
        uses: robinraju/release-downloader@v1.6
        with: 
          repository: "KinectToVR/plugin_OpenVR"
          latest: true
          fileName: "plugin_OpenVR.zip"
          out-file-path: "Pack/Zip/"
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Unpack downloaded plugins
        run: |
          7z x .\Pack\Zip\plugin_KinectV1.zip -oPack/Output/Plugins/KinectV1
          7z x .\Pack\Zip\plugin_KinectV2.zip -oPack/Output/Plugins/KinectV2
          7z x .\Pack\Zip\plugin_PSMoveService.zip -oPack/Output/Plugins/PSMoveService
          7z x .\Pack\Zip\plugin_owoTrackVR.zip -oPack/Output/Plugins/owoTrackVR
          7z x .\Pack\Zip\plugin_OpenVR.zip -oPack/Output/Plugins/OpenVR

      - name: Pack published files
        run: |
          cd Pack\Output
          7z a Amethyst.NET.zip *
        
      - name: Upload packed app artifact
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Amethyst.NET Build Artifact"
          files: "Pack/Output/Amethyst.NET.zip"